---
title: "BIOSTAT 707 Project: County FIPS Groups"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Load the Needed Libraries
library(tidyverse)
library(here)
```



```{r}
#Import the Analytic Data
Analytic_Data <-
  read.csv(here("df.csv"))

#Set a Seed for Reproducibility
set.seed(15)

#Randomly Order all of the County FIPS and Place in Data Frame
Groups_Data <-
  data.frame(sample(unique(Analytic_Data$County.FIPS),
                    length(unique(Analytic_Data$County.FIPS)),
                    replace = FALSE))

#Assign Group to County FIPS based on the Row Number
for (i in 1:nrow(Groups_Data)){
  if (i <= round(nrow(Groups_Data) / 10)) {Groups_Data[i, 2] <- 1} else
  if (i <= 2 * round(nrow(Groups_Data) / 10)) {Groups_Data[i, 2] <- 2} else 
  if (i <= 3 * round(nrow(Groups_Data) / 10)) {Groups_Data[i, 2] <- 3} else 
  if (i <= 4 * round(nrow(Groups_Data) / 10)) {Groups_Data[i, 2] <- 4} else 
  if (i <= 5 * round(nrow(Groups_Data) / 10)) {Groups_Data[i, 2] <- 5} else 
  if (i <= 6 * round(nrow(Groups_Data) / 10)) {Groups_Data[i, 2] <- 6} else 
  if (i <= 7 * round(nrow(Groups_Data) / 10)) {Groups_Data[i, 2] <- 7} else 
  if (i <= 8 * round(nrow(Groups_Data) / 10)) {Groups_Data[i, 2] <- 8} else 
  if (i <= 9 * round(nrow(Groups_Data) / 10)) {Groups_Data[i, 2] <- 9} else 
  {Groups_Data[i, 2] <- 10}
}

#Set Column Names
colnames(Groups_Data) <- c("County.FIPS", "County.FIPS.Group")

#Check the Number of Group Assignments
table(Groups_Data[, 2])

#Create New Column in Analytic Data
Analytic_Data$County.FIPS.Group <- NA

#Add Assignments to Analytic Data
for (i in 1:nrow(Analytic_Data)) {
  for (j in 1:nrow(Groups_Data)) {
    if (Analytic_Data$County.FIPS[i] == Groups_Data$County.FIPS[j]) {
      Analytic_Data$County.FIPS.Group[i] = Groups_Data$County.FIPS.Group[j]
    }
  }
  
  
  #Print Percent Complete
  if ((i / 100) == round(i / 100)) {
    #Clear Console
    cat("\014")
    
    #Print Percent Complete
    print(paste(round((i / nrow(Analytic_Data) * 100), 4), "% Complete", sep = ""))
  }
}
```